### PR TITLE
String update 2022/11/28

### PR DESCRIPTION
**Pull request by dan-alcantara-neeva**
* Update strings files based off of files pulled from Smartling on 2022-11-28.
* Add a script that extracts and puts the files in the right place.

### CODE REVIEW

**Review by Kokobe — APPROVED** [review]

**Review by andjd — CHANGES_REQUESTED** [review]
The spaces for the sentence separators need to be escaped (`\u0020` for a normal space) as the XML parser will strip leading and trailing whitespace.

**Comment by dan-alcantara-neeva** [comment]
Hrm.  If that were the case then Smartling's export is screwed up...

**Comment by dan-alcantara-neeva** [comment]
It's not even showing up in the Smartling dashboard, for some reason.

**Comment by dan-alcantara-neeva** [comment]
@andjd Gave up on Smartling trying to translate a space character and just said it's not a translatable string in our source file.  PTAL.

**Comment by andjd** [comment]
Question. If the strings are non-translatable, is there any reason to put them in the translated files?

**Comment by dan-alcantara-neeva** [comment]
> Question. If the strings are non-translatable, is there any reason to put them in the translated files?

Not normally, but the way Smartling works is that it takes your original `strings.xml` file (comments, non-translatable strings and all) and then replaces the original text with the translations.  So if I don't do it now, it'll just happen the next time we get translations again.

**Review by andjd — APPROVED** [review]

**Pull request merged**
