### PR TITLE
Sanitize Intents that are being passed in

### PR DESCRIPTION
**Pull request by dan-alcantara-neeva**
* Guard against unparcelable data being passed in by external apps via `Intent`s.
* Change how we detect whether we should reuse an `Intent` in `NeevaActivity` by looking at the `savedInstanceState`, which is not null if the app died in the background.

### How was this tested?
- [X] I tested this manually on `debug`
- [X] I tested this manually on `staging` or `release`
- [X] I added automated tests
- [X] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [X] I checked that `@Previews` still work in Android Studio

### Manual test cases
Fired external Intents at the app to open various websites, rotating the screen, and with `Don't Keep Activities` toggled on or off.

### Screenshots and recordings
[device-2022-10-20-162617.webm](https://user-images.githubusercontent.com/96092902/197077745-a94c5b2a-294d-4cd9-b3ed-e82d14b70481.webm)

### CODE REVIEW

**Comment by dan-alcantara-neeva** [comment]
@Kokobe Any chance you could give this a pass before we cut the nightly?

**Review by Kokobe — APPROVED** [review]

**Comment by Kokobe** [comment]
Make sure you test if opening downloads still works + check the release/staging versions too (because debug gets some weird extra permissions with intents from my experience)

**Review by Kokobe — CHANGES_REQUESTED** [review]
% lmk when you finish testing!

**Comment by dan-alcantara-neeva** [comment]
@Kokobe Ran it on staging, opened a link in GMail to open the browser, then opened downloads.  Movie attached to the original description

**Review by Kokobe — APPROVED** [review]

**Pull request merged**
