### PR TITLE
Fix spaceID AppNavModel compiler warning

### PR DESCRIPTION
**Pull request by Kokobe**
Fixes the following error by keeping the naming of `spaceId` consistent. 

```
w: /Users/danalcantara/projects/neeva-android-2/app/src/main/java/com/neeva/app/appnav/AppNavModelImpl.kt: (203, 38):
 The corresponding parameter in the supertype 'AppNavModel' is named 'spaceId'. 
This may cause problems when calling this function with named arguments.
```

### CODE REVIEW

**Comment by dan-alcantara-neeva** [comment]
Eh, fixing this particular compiler warning shouldn't need a "tentative" PR.  You can compile it locally and check it yourself

**Comment by Kokobe** [comment]
Hmmm I wasn't actually able to reproduce the warning locally (building and compiling the project didn't show anything in Logcat for me. 

How did you produce it?

**Comment by Kokobe** [comment]
Nevermind! Just produced it by resetting my cache.

**Comment by dan-alcantara-neeva** [comment]
Logcat only shows messages from your device.  You should be checking the compiler warnings in Android Studio itself.  This message came out after syncing up to your PR and trying to build the release branch from the command line, but Android Studio shows it in the build output window.  The parameter generating the warning also gets highlighted in the UI.

Screen Shot 2022-09-23 at 6 02 31 PM

**Comment by Kokobe** [comment]
Confirmed that it fixed the compiler error!

**Comment by dan-alcantara-neeva** [comment]
> Confirmed that it fixed the compiler error!

Compiler *warning.  I want to make the warnings errors eventually, but haven't looked into what setting we need to set yet.

**Review by dan-alcantara-neeva — APPROVED** [review]

**Pull request merged**
